### ISSUE TITLE
Ip address 

### ISSUE THREAD

**Issue by timother** [JBrookshaw/node-wARriorDrone#1]
hi, i know its possible to change the ip when you create your ar-drone client. but when i do it your application still use the defaults ip. Is it normal and is there a way to change that.

**Comment by JBrookshaw** [comment]
Were you able to figure this out?  I never tried changing the IP address but I know it can be done.

**Comment by timother** [comment]
Hi jeff,

I was wondering how you get the getDataImage working in the detectColor funtion in the main.js file. I notice that the function was missing from the default dronestream package so i put it in it but it still doesn't work

---

De : Jeff Brookshaw notifications@github.com
Envoyé : 20 avril 2016 12:25
À : JBrookshaw/node-wARriorDrone
Cc : timother; State change
Objet : Re: [JBrookshaw/node-wARriorDrone] Ip address (#1)

Were you able to figure this out? I never tried changing the IP address but I know it can be done.

##
